import type {
  Article,
  AboutProfile,
  Engagement,
  Expertise,
  ExternalProfile,
  Interest,
  LinkItem,
  Location,
  Photograph,
  PrintProduct,
  Service,
  Training,
  WorkItem,
} from "./types";

export const site = {
  name: "Cheesewiththat",
  title: "Mihir—with context.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://cheesewiththat.com",
  description:
    "Mihir builds products, commercialises technology and makes complicated systems useful.",
};
export const externalProfiles: ExternalProfile[] = [
  {
    id: "linkedin",
    label: "LinkedIn",
    href: "https://www.linkedin.com/in/mihirsatokar/",
    configured: true,
  },
  { id: "facebook", label: "Facebook", configured: false },
  {
    id: "x",
    label: "X",
    href: "https://x.com/cheesewiththat",
    configured: true,
  },
  {
    id: "instagram",
    label: "Instagram",
    href: "https://www.instagram.com/cheesewiththat",
    configured: true,
  },
  {
    id: "github",
    label: "GitHub",
    href: "https://github.com/cheesewiththat",
    configured: true,
  },
  {
    id: "current-work",
    label: "Current company",
    href: "https://cloudsmartz.com/contact-us/",
    configured: true,
  },
  {
    id: "previous-blog",
    label: "Previous blog",
    href: "https://mihirspeaks.blogspot.com",
    configured: true,
  },
  {
    id: "zero-one-products",
    label: "0–1 Products",
    href: "https://0-1products.com",
    configured: true,
  },
];
export const navigation: LinkItem[] = [
  { label: "Mihir", href: "/mihir" },
  { label: "Work", href: "/work" },
  { label: "Ideas", href: "/ideas" },
  { label: "Map", href: "/map" },
  { label: "Photography", href: "/photography" },
  { label: "Collect", href: "/collect" },
  { label: "Engage", href: "/engage" },
];
export const roles = [
  {
    title: "Builder",
    body: "Turning ambiguous problems into useful products, systems and momentum.",
  },
  {
    title: "Operator",
    body: "Making complex programmes legible, governable and deliverable.",
  },
  {
    title: "Commercial Leader",
    body: "Connecting customer reality, product decisions and routes to market.",
  },
  {
    title: "Advisor",
    body: "Bringing a calm, independent view to difficult decisions.",
  },
];
export const aboutMihir: AboutProfile = {
  heading: "A little about me",
  paragraphs: [
    "I’m Mihir — a product, technology and commercial leader who has spent much of his career working at the intersection of telecom, software, transformation and new product development. I’ve helped shape and deliver complex platforms across OSS/BSS, connectivity, digital marketplaces, CPQ, network operations and AI-enabled products, often moving between product strategy, solution design, delivery, partnerships, sales and customer leadership depending on what the situation actually needs.",
    "I enjoy taking complicated ideas and turning them into something clearer, more practical and commercially useful. That might mean helping a company modernise a telecom stack, breaking down an early-stage product idea, shaping a go-to-market plan, rescuing a difficult programme or working with teams to make AI useful without turning it into theatre. I’m equally comfortable in a boardroom, a product workshop, a customer meeting or deep in a conversation about architecture, APIs and why six integrations somehow became twelve.",
    "Outside work, I’m a traveller, photographer, F1 follower, car enthusiast and collector of oddly specific facts. I like cities, stories, machines, maps, good design and people who are building something interesting. Cheesewiththat is where all of those sides come together — the professional work, the ideas, the things I’m learning, the places I’ve been and the occasional unnecessary opinion.",
  ],
  portrait: {
    src: "/images/mihir/mihir-waterfront.png",
    alt: "Portrait of Mihir by the water",
    width: 800,
    height: 800,
    caption:
      "Usually somewhere between a product workshop, an airport lounge and an argument about engines.",
  },
};
export const expertise: Expertise[] = [
  [
    "Product Strategy and 0–1 Product Building",
    "From problem definition to a credible first release.",
  ],
  ["AI Product Management", "Useful AI products with sensible human controls."],
  [
    "AI Project and Program Management",
    "Delivery plans that account for data, adoption, governance and cost.",
  ],
  [
    "Telecom OSS/BSS Transformation",
    "Modernising the machinery behind connectivity.",
  ],
  [
    "CPQ and Quote-to-Cash",
    "Making complex propositions easier to configure, sell and fulfil.",
  ],
  [
    "Network Observability and AIOps",
    "Turning operational signals into decisions and action.",
  ],
  [
    "Connectivity Solution Architecture",
    "Joining commercial intent to technical feasibility.",
  ],
  [
    "GTM and Commercial Strategy",
    "Positioning, packaging and routes to market.",
  ],
  [
    "Complex Program Delivery",
    "Structure and recovery for multi-party change.",
  ],
].map(([title, description]) => ({ title, description }));
export const work: WorkItem[] = [
  [
    "airline-marketplace",
    "Global Airline Digital Marketplace",
    "A demonstration of how a multi-partner marketplace case study could explain product, commercial and integration decisions.",
    ["Product", "Marketplace", "Integration"],
  ],
  [
    "quote-to-cash",
    "Telecom Quote-to-Cash Modernisation",
    "A sample structure for connecting customer journeys with catalogue, pricing, orchestration and operations.",
    ["Telecom", "CPQ", "Transformation"],
  ],
  [
    "network-operations",
    "AI-Assisted Network Operations",
    "A sample exploration of safe, operator-centred AI workflows for complex network environments.",
    ["AI", "AIOps", "Operations"],
  ],
  [
    "field-platform",
    "Field Operations and Fibre Maintenance Platform",
    "A sample product narrative spanning field teams, workflow, evidence and service assurance.",
    ["0–1", "Field operations", "Fibre"],
  ],
  [
    "carrier-api",
    "Carrier API Interoperability",
    "A sample architecture narrative for consistent partner experiences across heterogeneous carrier APIs.",
    ["APIs", "Ecosystems", "Connectivity"],
  ],
].map(([slug, title, summary, disciplines]) => ({
  slug: slug as string,
  title: title as string,
  summary: summary as string,
  disciplines: disciplines as string[],
  sample: true,
}));
export const interests: Interest[] = [
  {
    label: "Building",
    value: "A more useful home for all the work and wandering.",
  },
  {
    label: "Thinking about",
    value: "Where AI genuinely changes the product, not merely the pitch.",
  },
  {
    label: "Reading",
    value:
      "A rotating stack of systems, cities and wonderfully specific obsessions.",
  },
  {
    label: "Watching",
    value: "Formula 1, with an unreasonable interest in strategy calls.",
  },
  { label: "Learning", value: "Better ways to make complex ideas tangible." },
  {
    label: "Travelling",
    value: "Between familiar places and the next good long walk.",
  },
  {
    label: "Obsessing over unnecessarily",
    value: "The tiny details that make an interface—or an engine—feel right.",
  },
];
export const engagements: Engagement[] = [
  {
    slug: "direction-check",
    title: "15-minute Direction Check",
    duration: "15 min",
    description: "A quick fit check for a clearly framed decision.",
    mode: "preview",
  },
  {
    slug: "expert-session",
    title: "30-minute Expert Session",
    duration: "30 min",
    description: "Focused perspective on a product, AI or telecom question.",
    mode: "preview",
  },
  {
    slug: "working-session",
    title: "60-minute Working Session",
    duration: "60 min",
    description: "Work through a problem and leave with practical next moves.",
    mode: "preview",
  },
  {
    slug: "idea-clinic",
    title: "90-minute Idea Lab",
    duration: "90 min",
    description: "Pressure-test an idea, proposition, roadmap or programme.",
    mode: "preview",
  },
];
export const services: Service[] = [
  {
    slug: "product",
    title: "Product and 0–1 Building",
    intro: "Make the problem and first product concrete.",
    capabilities: [
      "Idea evaluation",
      "Problem definition",
      "Product strategy",
      "MVP definition",
      "Product roadmap",
      "Prototype and validation planning",
    ],
  },
  {
    slug: "ai",
    title: "AI Product and Delivery Advisory",
    intro: "Move from AI enthusiasm to a governable product and delivery plan.",
    capabilities: [
      "AI use-case identification",
      "AI readiness",
      "AI product strategy",
      "Agentic workflow design",
      "Human-in-the-loop models",
      "AI program planning",
      "Governance, adoption and cost",
    ],
  },
  {
    slug: "telecom",
    title: "Telecom and Connectivity Consulting",
    intro:
      "Navigate the operational and commercial machinery behind connectivity.",
    capabilities: [
      "OSS/BSS modernisation",
      "CPQ and quote-to-cash",
      "Service inventory",
      "Digital marketplaces",
      "Partner ecosystems",
      "Network observability and AIOps",
      "API interoperability",
      "TM Forum, MEF and CAMARA-aligned integration",
      "Connectivity solution architecture",
    ],
  },
  {
    slug: "program",
    title: "Program and Project Advisory",
    intro: "Bring structure and momentum to complex delivery.",
    capabilities: [
      "Complex program planning",
      "Delivery governance",
      "Scope and milestone definition",
      "Vendor coordination",
      "Stakeholder management",
      "Program recovery",
    ],
  },
  {
    slug: "commercial",
    title: "Commercial and GTM Advisory",
    intro:
      "Connect positioning and propositions with how customers actually buy.",
    capabilities: [
      "Product positioning",
      "GTM planning",
      "B2B acquisition journeys",
      "Product commercialisation",
      "Proposal strategy",
      "Partner strategy",
      "Sales and product alignment",
    ],
  },
];
export const training: Training[] = [
  "Product Management Fundamentals",
  "AI Product Management",
  "AI Project Management",
  "Telecom Software and OSS/BSS Fundamentals",
  "Connectivity Solution Architecture",
  "From Idea to MVP",
].map((title, index) => ({
  slug: `programme-${index + 1}`,
  title,
  audience: "Teams and leaders who want practical, shared language and tools.",
  outcomes: [
    "A usable mental model",
    "Techniques that transfer to current work",
    "A concrete next-step plan",
  ],
  durations: ["Half-day", "Full-day", "Multi-week"],
  modes: [
    "One-to-one coaching",
    "Corporate workshop",
    "Conference session",
    "Guest lecture",
  ],
}));
export const locations: Location[] = [
  {
    id: "nagpur",
    name: "Nagpur",
    country: "India",
    region: "Maharashtra",
    coordinates: [21.1458, 79.0882],
    category: "lived",
    sequence: 1,
    approximateDuration: "Multiple chapters",
    context: "Birth, schooling and engineering chapters.",
    chapters: [
      {
        label: "Birth and first home",
        approximateDuration: "About 1 year",
        context:
          "Born in Nagpur and lived there for approximately the first year of his life.",
        sequence: 1,
      },
      {
        label: "Schooling return",
        approximateDuration: "Approx. 1.5 years",
        context: "Returned to Nagpur for approximately 1.5 years of schooling.",
        sequence: 4,
      },
      {
        label: "Engineering",
        approximateDuration: "About 4 years",
        context: "Returned again for approximately 4 years of engineering.",
        sequence: 7,
      },
    ],
    current: false,
    publicationStatus: "public",
    verified: true,
  },
  {
    id: "delhi",
    name: "Delhi",
    country: "India",
    region: "Delhi",
    coordinates: [28.6139, 77.209],
    category: "lived",
    sequence: 2,
    approximateDuration: "Multiple chapters",
    context: "Early childhood, a later return and a work chapter.",
    chapters: [
      {
        label: "Early childhood",
        approximateDuration: "About 4.5 years",
        context:
          "Moved to Delhi at approximately age 1 and lived there during early childhood.",
        sequence: 2,
      },
      {
        label: "Later return",
        approximateDuration: "About 4 years",
        context: "Returned to Delhi for approximately 4 years.",
        sequence: 6,
      },
      {
        label: "Work chapter",
        approximateDuration: "About 6 years",
        context: "Returned again for approximately 6 years for work.",
        sequence: 10,
      },
    ],
    current: false,
    publicationStatus: "public",
    verified: true,
  },
  {
    id: "colombo",
    name: "Colombo",
    country: "Sri Lanka",
    coordinates: [6.9271, 79.8612],
    category: "lived",
    sequence: 3,
    approximateDuration: "About 5 years",
    context:
      "Lived in Colombo and attended school there. About one year overlaps with the later Nagpur schooling chapter.",
    chapters: [
      {
        label: "School years",
        approximateDuration: "About 5 years",
        context: "Lived in Colombo and attended school there.",
        sequence: 3,
      },
    ],
    current: false,
    publicationStatus: "public",
    verified: true,
  },
  {
    id: "mumbai",
    name: "Mumbai",
    country: "India",
    region: "Maharashtra",
    coordinates: [19.076, 72.8777],
    category: "lived",
    sequence: 5,
    approximateDuration: "About 3 years",
    context: "Primarily a schooling period.",
    chapters: [
      {
        label: "Schooling",
        approximateDuration: "About 3 years",
        context: "Lived in Mumbai, primarily for schooling.",
        sequence: 5,
      },
    ],
    current: false,
    publicationStatus: "public",
    verified: true,
  },
  {
    id: "glasgow",
    name: "Glasgow",
    country: "Scotland",
    coordinates: [55.8642, -4.2518],
    category: "lived",
    sequence: 8,
    approximateDuration: "Approx. 2.5 years",
    context: "Completed a master’s degree and also worked there.",
    chapters: [
      {
        label: "Master’s and work",
        approximateDuration: "Approx. 2.5 years",
        context:
          "Completed a master’s degree in Glasgow and also worked there.",
        sequence: 8,
      },
    ],
    current: false,
    publicationStatus: "public",
    verified: true,
  },
  {
    id: "london",
    name: "London",
    country: "England",
    coordinates: [51.5074, -0.1278],
    category: "lived",
    sequence: 9,
    approximateDuration: "About 6 months",
    context: "Lived and worked there.",
    chapters: [
      {
        label: "Work chapter",
        approximateDuration: "About 6 months",
        context: "Lived in London and worked there.",
        sequence: 9,
      },
    ],
    current: false,
    publicationStatus: "public",
    verified: true,
  },
  {
    id: "chandigarh",
    name: "Chandigarh",
    country: "India",
    coordinates: [30.7333, 76.7794],
    category: "lived",
    sequence: 11,
    approximateDuration: "About 6 years",
    context: "A work and life chapter.",
    chapters: [
      {
        label: "Work and life",
        approximateDuration: "About 6 years",
        context: "Lived in Chandigarh during a work and life chapter.",
        sequence: 11,
      },
    ],
    current: false,
    publicationStatus: "public",
    verified: true,
  },
  {
    id: "melbourne",
    name: "Melbourne",
    country: "Australia",
    region: "Victoria",
    coordinates: [-37.8136, 144.9631],
    category: "lived",
    sequence: 12,
    approximateDuration: "About 1 year",
    context: "Mihir’s first home in Australia.",
    chapters: [
      {
        label: "First Australian home",
        approximateDuration: "About 1 year",
        context: "Melbourne was Mihir’s first home in Australia.",
        sequence: 12,
      },
    ],
    current: false,
    publicationStatus: "public",
    verified: true,
  },
  {
    id: "wangaratta",
    name: "Wangaratta",
    country: "Australia",
    region: "Victoria",
    coordinates: [-36.358, 146.325],
    category: "lived",
    sequence: 13,
    approximateDuration: "About 2 years and current",
    context: "Mihir’s current home, shown at city level only.",
    chapters: [
      {
        label: "Current home",
        approximateDuration: "About 2 years and current",
        context: "Currently lives in Wangaratta.",
        sequence: 13,
      },
    ],
    current: true,
    publicationStatus: "public",
    verified: true,
  },
  ...[
    ["reston", "Reston", "United States", "Virginia", 38.9586, -77.357],
    [
      "new-york-city",
      "New York City",
      "United States",
      "New York",
      40.7128,
      -74.006,
    ],
    [
      "san-diego",
      "San Diego",
      "United States",
      "California",
      32.7157,
      -117.1611,
    ],
    [
      "los-angeles",
      "Los Angeles",
      "United States",
      "California",
      34.0522,
      -118.2437,
    ],
    ["carlsbad", "Carlsbad", "United States", "California", 33.1581, -117.3506],
    [
      "washington-dc",
      "Washington, D.C.",
      "United States",
      "District of Columbia",
      38.9072,
      -77.0369,
    ],
    ["stuttgart", "Stuttgart", "Germany", undefined, 48.7758, 9.1829],
    ["edinburgh", "Edinburgh", "Scotland", undefined, 55.9533, -3.1883],
    ["manchester", "Manchester", "England", undefined, 53.4808, -2.2426],
    ["dubai", "Dubai", "United Arab Emirates", undefined, 25.2048, 55.2708],
    ["riyadh", "Riyadh", "Saudi Arabia", undefined, 24.7136, 46.6753],
    ["hong-kong", "Hong Kong", "Hong Kong", undefined, 22.3193, 114.1694],
    ["bali", "Bali", "Indonesia", undefined, -8.4095, 115.1889],
    ["phuket", "Phuket", "Thailand", undefined, 7.8804, 98.3923],
    ["bangkok", "Bangkok", "Thailand", undefined, 13.7563, 100.5018],
    [
      "phi-phi-islands",
      "Phi Phi Islands",
      "Thailand",
      undefined,
      7.7407,
      98.7784,
    ],
  ].map(([id, name, country, region, latitude, longitude]) => ({
    id: id as string,
    name: name as string,
    country: country as string,
    region: region as string | undefined,
    coordinates: [latitude as number, longitude as number] as [number, number],
    category: "travelled" as const,
    context: "Confirmed travel location.",
    chapters: [],
    current: false,
    publicationStatus: "public" as const,
    verified: true,
  })),
];
export const photographs: Photograph[] = [
  {
    id: "p1",
    slug: "blue-hour",
    title: "Blue Hour, Held",
    description: "A study in windows and dusk.",
    story:
      "Placeholder artwork marks the intended editorial rhythm until an approved photograph is supplied.",
    location: "Melbourne",
    country: "Australia",
    year: 2025,
    image: "/images/blue-hour.svg",
    thumbnail: "/images/blue-hour.svg",
    width: 1200,
    height: 1500,
    orientation: "portrait",
    alt: "Abstract cobalt windows against a warm dusk field",
    categories: ["Cities", "Architecture", "Australia"],
    featured: true,
    availableAsPrint: true,
    printProduct: "blue-hour-print",
    mapLocation: "melbourne",
    visibility: "public",
  },
  {
    id: "p2",
    slug: "monsoon-lines",
    title: "Monsoon Lines",
    description: "Movement, rain and reflected vermilion.",
    story: "Placeholder artwork for a future street photograph.",
    location: "Mumbai",
    country: "India",
    year: 2024,
    image: "/images/monsoon-lines.svg",
    thumbnail: "/images/monsoon-lines.svg",
    width: 1600,
    height: 1000,
    orientation: "landscape",
    alt: "Abstract rain lines and a vermilion reflection",
    categories: ["Street", "India", "Black and White"],
    featured: true,
    availableAsPrint: false,
    mapLocation: "mumbai",
    visibility: "public",
  },
  {
    id: "p3",
    slug: "geometry",
    title: "Useful Geometry",
    description: "Concrete, shade and deliberate green.",
    story: "Placeholder artwork for a future architecture photograph.",
    location: "Singapore",
    country: "Singapore",
    year: 2023,
    image: "/images/geometry.svg",
    thumbnail: "/images/geometry.svg",
    width: 1200,
    height: 1200,
    orientation: "square",
    alt: "Abstract teal architectural planes with a chartreuse detail",
    categories: ["Architecture", "Travel", "Details and Textures"],
    featured: true,
    availableAsPrint: true,
    printProduct: "geometry-print",
    visibility: "public",
  },
];
export const prints: PrintProduct[] = [
  {
    id: "blue-hour-print",
    slug: "blue-hour-print",
    photograph: "p1",
    title: "Blue Hour, Held",
    description:
      "An editorial print preview in the Cities I’ve Carried Back collection.",
    story:
      "Final paper, dimensions and edition details will be confirmed before orders open.",
    collection: "Cities I’ve Carried Back",
    edition: "signature",
    sizes: ["A3", "A2", "A1"],
    materials: ["Archival fine-art paper"],
    framed: true,
    currency: "AUD",
    shippingRegions: ["Australia (planned)"],
    availability: "interest",
    featured: true,
    status: "preview",
    seo: {
      title: "Blue Hour, Held print",
      description:
        "Register interest in this planned fine-art photography print.",
    },
  },
  {
    id: "geometry-print",
    slug: "geometry-print",
    photograph: "p3",
    title: "Useful Geometry",
    description: "A print preview from Quiet Frames.",
    story:
      "A calm architectural study; production specifications remain intentionally uncommitted.",
    collection: "Quiet Frames",
    edition: "open",
    sizes: ["A3", "A2"],
    materials: ["Archival fine-art paper"],
    framed: false,
    currency: "AUD",
    shippingRegions: ["Australia (planned)"],
    availability: "interest",
    featured: true,
    status: "preview",
    seo: {
      title: "Useful Geometry print",
      description: "Register interest in this planned architecture print.",
    },
  },
];
export const articles: Article[] = [
  {
    slug: "ai-without-the-theatre",
    title: "AI without the theatre: start with the work",
    excerpt:
      "A sample editorial structure for discussing AI in terms of decisions, workflows and responsibility—not stagecraft.",
    author: "Mihir",
    published: "2026-07-01",
    category: "AI Without the Theatre",
    tags: ["AI", "Product", "Delivery"],
    readingTime: "4 min",
    featured: true,
    relatedServices: ["ai"],
    relatedProjects: [],
    relatedLocations: [],
    seo: {
      title: "AI without the theatre",
      description:
        "A sample article about finding useful AI product opportunities.",
    },
    draft: false,
    sample: true,
    sections: [
      {
        heading: "Begin with friction",
        body: "The useful question is rarely “Where can we add AI?” It is “Where does valuable work currently stall, repeat or lose context?”",
      },
      {
        heading: "Design the decision",
        body: "A model output is not a product outcome. Define who decides, what evidence they need and how uncertainty remains visible.",
      },
      {
        heading: "Earn the automation",
        body: "Start with assistance, instrument the workflow and expand autonomy only when the evidence and controls justify it.",
      },
    ],
  },
];
